# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - msa-frontend-molina

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-deploy:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: "./frontend"

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: msa-frontend-molina
        slot-name: Production
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4082cae1dec2419ca6524c44fc8fd07a }}
          package: "./frontend/build"
